---
- name: Kubeadm Setup for Ubuntu 24.04 LTS
  hosts: all
  become: yes
  vars:
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade the system
      apt:
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - containerd
        state: present
    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        systemctl restart containerd


    - name: Download and add Kubernetes repository key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository to sources list
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt package index
      shell: apt update -y

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
    
    - name: Hold Kubernetes packages
      shell: |
        apt-mark hold kubelet kubeadm kubectl

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set sysctl parameters
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
    
    - name: Apply sysctl settings
      shell: sysctl --system

- name: Kubeadm initialisation
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.1.0.0/16

    - name: Set up kubeconfig for user
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Flannel network plugin
      command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    - name: Get kubeadm join command from master
      command: kubeadm token create --print-join-command
      register: join_command
    - name: Display join commad
      ansible.builtin.debug:
                        msg: "{{ join_command.stdout }}"
    - name: Share join command with worker nodes
      add_host:
        name: "all_workers"
        kube_join_cmd: "{{ join_command.stdout }}"

- name: Joining the cluster
  hosts: worker
  become: yes
  tasks:
    - name: Ensure kube_join_cmd variable is available
      set_fact:
        kube_join_cmd: "{{ hostvars['all_workers']['kube_join_cmd'] }}"

    - name: Join worker nodes to the cluster
      command: "{{ kube_join_cmd }}"
